### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by pza007** [pza007/game_bot#6]
- [ ] Assign new ID's for new objects
- [ ] "Hold on" time for lost objects
- [ ] Delete old objects
